[package]
name = "pathtracer"
version = "0.1.0"
authors = ["Dennis Kristiansen <dennkris@live.no>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lazy_static = "1.4.0"
rayon = "1.3.0"
glutin = "0.24.0"
image = "0.23.4"
glam = "0.8.7"
rand = "0.7.3"
rand_distr = "0.2.2"
rand_xoshiro = "0.4.0"

[build-dependencies]
anyhow = "1.0.28"
gl_generator = "0.14.0"

[profile.dev]
opt-level = 2
debug = true
